FROM node:20

WORKDIR /react/

RUN npm i

CMD ["npm", "start"]

#To start it all you need two commands :

#First :  docker build -t marvfront:0.1 -f Dockerfile.front .
#This one is used to create the docker image

#Second : docker run -p "3000:3000" marvfront:0.1
#This second one is to create a container from the existing image

