version: '4'
services:
  marvfront:
    image: marvfront:0.1
    environment:
      PORT: 3000
    ports:
      - 3000:3000
  marvback:
    image: marvback:0.1
    environment:
      PORT: 5000
    ports:
      - 5000:5000