FROM node:20

WORKDIR /react/

COPY ./front/package.json /react/

RUN npm i

COPY ./front/public /react/public
COPY ./front/src /react/src
COPY ./front/ /react/

CMD ["npm", "start"]

#To start it, all you are (is ?) need two commands :

#First :  docker build -t marvfront:0.1 -f Dockerfile.front .
#This one is used to create the docker image

#Second : docker run -p "3000:3000" marvfront:0.1
#This second one is to create a container from the existing image

